name: Update pack

#trigger on push
on:
  push:
    branches: [ "main" ]
    paths: [ "pack/**" ]

  workflow_dispatch:


jobs:

  #run zip
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update zip archive
        run: |
          mkdir -p export
          cd pack && zip -r ../export/pack.zip .
  #possible upload to external server in future
